# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Deploy main application
        run: |
          echo "Deploying main application..."
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      
      - name: Health check
        run: |
          echo "Waiting for deployment to stabilize..."
          sleep 30
          echo "Checking application health..."
          response=$(curl -s -w "\n%{http_code}" https://trading-assistant-divine-frost-7376.fly.dev/api/health)
          status=$(echo "$response" | tail -n1)
          body=$(echo "$response" | head -n1)
          
          if [ "$status" -ne 200 ]; then
            echo "Health check failed with status $status"
            echo "Response: $body"
            exit 1
          fi
          
          if echo "$body" | grep -q '"status":"error\|degraded"'; then
            echo "Service is not healthy"
            echo "Response: $body"
            exit 1
          fi
          
          echo "Health check passed"
